# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BatWindow.ui'
#
# Created: Mon Mar  9 18:39:52 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_BatWindow(object):
    def setupUi(self, BatWindow):
        BatWindow.setObjectName(_fromUtf8("BatWindow"))
        BatWindow.resize(1225, 959)
        self.centralwidget = QtGui.QWidget(BatWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1201, 941))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_analyze = QtGui.QWidget()
        self.tab_analyze.setObjectName(_fromUtf8("tab_analyze"))
        self.button_start = QtGui.QPushButton(self.tab_analyze)
        self.button_start.setGeometry(QtCore.QRect(765, 700, 181, 51))
        self.button_start.setObjectName(_fromUtf8("button_start"))
        self.progressBar_analyse = QtGui.QProgressBar(self.tab_analyze)
        self.progressBar_analyse.setGeometry(QtCore.QRect(95, 440, 991, 23))
        self.progressBar_analyse.setProperty("value", 0)
        self.progressBar_analyse.setObjectName(_fromUtf8("progressBar_analyse"))
        self.textEdit_overview = QtGui.QTextEdit(self.tab_analyze)
        self.textEdit_overview.setGeometry(QtCore.QRect(95, 50, 991, 371))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_overview.setFont(font)
        self.textEdit_overview.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.textEdit_overview.setReadOnly(True)
        self.textEdit_overview.setObjectName(_fromUtf8("textEdit_overview"))
        self.label_status = QtGui.QLabel(self.tab_analyze)
        self.label_status.setGeometry(QtCore.QRect(95, 30, 66, 17))
        self.label_status.setObjectName(_fromUtf8("label_status"))
        self.pushButton_createSpectrogram = QtGui.QPushButton(self.tab_analyze)
        self.pushButton_createSpectrogram.setGeometry(QtCore.QRect(205, 700, 181, 51))
        self.pushButton_createSpectrogram.setObjectName(_fromUtf8("pushButton_createSpectrogram"))
        self.pushButton_SetInputDirectory = QtGui.QPushButton(self.tab_analyze)
        self.pushButton_SetInputDirectory.setGeometry(QtCore.QRect(105, 490, 171, 31))
        self.pushButton_SetInputDirectory.setObjectName(_fromUtf8("pushButton_SetInputDirectory"))
        self.pushButton_SetOutputDirectory = QtGui.QPushButton(self.tab_analyze)
        self.pushButton_SetOutputDirectory.setGeometry(QtCore.QRect(105, 600, 171, 31))
        self.pushButton_SetOutputDirectory.setObjectName(_fromUtf8("pushButton_SetOutputDirectory"))
        self.label_inputDirectory = QtGui.QLabel(self.tab_analyze)
        self.label_inputDirectory.setGeometry(QtCore.QRect(105, 530, 811, 20))
        self.label_inputDirectory.setObjectName(_fromUtf8("label_inputDirectory"))
        self.line_17 = QtGui.QFrame(self.tab_analyze)
        self.line_17.setGeometry(QtCore.QRect(105, 570, 961, 16))
        self.line_17.setFrameShape(QtGui.QFrame.HLine)
        self.line_17.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_17.setObjectName(_fromUtf8("line_17"))
        self.label_outputDirectory = QtGui.QLabel(self.tab_analyze)
        self.label_outputDirectory.setGeometry(QtCore.QRect(105, 640, 811, 20))
        self.label_outputDirectory.setObjectName(_fromUtf8("label_outputDirectory"))
        self.line_18 = QtGui.QFrame(self.tab_analyze)
        self.line_18.setGeometry(QtCore.QRect(105, 680, 961, 16))
        self.line_18.setFrameShape(QtGui.QFrame.HLine)
        self.line_18.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_18.setObjectName(_fromUtf8("line_18"))
        self.label_Channel = QtGui.QLabel(self.tab_analyze)
        self.label_Channel.setGeometry(QtCore.QRect(60, 770, 111, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_Channel.setFont(font)
        self.label_Channel.setObjectName(_fromUtf8("label_Channel"))
        self.frame_rbChannel = QtGui.QFrame(self.tab_analyze)
        self.frame_rbChannel.setGeometry(QtCore.QRect(205, 760, 181, 131))
        self.frame_rbChannel.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_rbChannel.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_rbChannel.setObjectName(_fromUtf8("frame_rbChannel"))
        self.radioButton_channel_1 = QtGui.QRadioButton(self.frame_rbChannel)
        self.radioButton_channel_1.setGeometry(QtCore.QRect(10, 10, 116, 22))
        self.radioButton_channel_1.setChecked(True)
        self.radioButton_channel_1.setObjectName(_fromUtf8("radioButton_channel_1"))
        self.radioButton_channel_2 = QtGui.QRadioButton(self.frame_rbChannel)
        self.radioButton_channel_2.setGeometry(QtCore.QRect(10, 40, 116, 22))
        self.radioButton_channel_2.setObjectName(_fromUtf8("radioButton_channel_2"))
        self.radioButton_channel_3 = QtGui.QRadioButton(self.frame_rbChannel)
        self.radioButton_channel_3.setGeometry(QtCore.QRect(10, 70, 116, 22))
        self.radioButton_channel_3.setObjectName(_fromUtf8("radioButton_channel_3"))
        self.radioButton_channel_4 = QtGui.QRadioButton(self.frame_rbChannel)
        self.radioButton_channel_4.setGeometry(QtCore.QRect(10, 100, 116, 22))
        self.radioButton_channel_4.setObjectName(_fromUtf8("radioButton_channel_4"))
        self.tabWidget.addTab(self.tab_analyze, _fromUtf8(""))
        self.tab_label = QtGui.QWidget()
        self.tab_label.setObjectName(_fromUtf8("tab_label"))
        self.button_loaddatabase = QtGui.QPushButton(self.tab_label)
        self.button_loaddatabase.setGeometry(QtCore.QRect(30, 10, 131, 41))
        self.button_loaddatabase.setObjectName(_fromUtf8("button_loaddatabase"))
        self.label_database_name = QtGui.QLabel(self.tab_label)
        self.label_database_name.setGeometry(QtCore.QRect(170, 20, 611, 17))
        self.label_database_name.setObjectName(_fromUtf8("label_database_name"))
        self.frame_status = QtGui.QFrame(self.tab_label)
        self.frame_status.setGeometry(QtCore.QRect(870, 30, 301, 871))
        self.frame_status.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_status.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_status.setObjectName(_fromUtf8("frame_status"))
        self.label_ConstEventName = QtGui.QLabel(self.frame_status)
        self.label_ConstEventName.setGeometry(QtCore.QRect(10, 10, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstEventName.setFont(font)
        self.label_ConstEventName.setObjectName(_fromUtf8("label_ConstEventName"))
        self.line = QtGui.QFrame(self.frame_status)
        self.line.setGeometry(QtCore.QRect(10, 50, 281, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_ConstEventNo = QtGui.QLabel(self.frame_status)
        self.label_ConstEventNo.setGeometry(QtCore.QRect(10, 60, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstEventNo.setFont(font)
        self.label_ConstEventNo.setObjectName(_fromUtf8("label_ConstEventNo"))
        self.line_2 = QtGui.QFrame(self.frame_status)
        self.line_2.setGeometry(QtCore.QRect(10, 100, 231, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label_ConstDate = QtGui.QLabel(self.frame_status)
        self.label_ConstDate.setGeometry(QtCore.QRect(10, 110, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstDate.setFont(font)
        self.label_ConstDate.setObjectName(_fromUtf8("label_ConstDate"))
        self.line_3 = QtGui.QFrame(self.frame_status)
        self.line_3.setGeometry(QtCore.QRect(10, 150, 231, 16))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.label_EventName = QtGui.QLabel(self.frame_status)
        self.label_EventName.setGeometry(QtCore.QRect(10, 30, 281, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_EventName.setFont(font)
        self.label_EventName.setObjectName(_fromUtf8("label_EventName"))
        self.label_EventNo = QtGui.QLabel(self.frame_status)
        self.label_EventNo.setGeometry(QtCore.QRect(10, 80, 231, 17))
        self.label_EventNo.setObjectName(_fromUtf8("label_EventNo"))
        self.label_Date = QtGui.QLabel(self.frame_status)
        self.label_Date.setGeometry(QtCore.QRect(10, 130, 231, 17))
        self.label_Date.setObjectName(_fromUtf8("label_Date"))
        self.line_4 = QtGui.QFrame(self.frame_status)
        self.line_4.setGeometry(QtCore.QRect(10, 310, 231, 16))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.label_maxFreq = QtGui.QLabel(self.frame_status)
        self.label_maxFreq.setGeometry(QtCore.QRect(10, 240, 231, 17))
        self.label_maxFreq.setObjectName(_fromUtf8("label_maxFreq"))
        self.label_ConstMaxFreq = QtGui.QLabel(self.frame_status)
        self.label_ConstMaxFreq.setGeometry(QtCore.QRect(10, 220, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstMaxFreq.setFont(font)
        self.label_ConstMaxFreq.setObjectName(_fromUtf8("label_ConstMaxFreq"))
        self.label_MinFreq = QtGui.QLabel(self.frame_status)
        self.label_MinFreq.setGeometry(QtCore.QRect(10, 290, 231, 17))
        self.label_MinFreq.setObjectName(_fromUtf8("label_MinFreq"))
        self.line_5 = QtGui.QFrame(self.frame_status)
        self.line_5.setGeometry(QtCore.QRect(10, 250, 231, 16))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.label_ConstMinFreq = QtGui.QLabel(self.frame_status)
        self.label_ConstMinFreq.setGeometry(QtCore.QRect(10, 270, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstMinFreq.setFont(font)
        self.label_ConstMinFreq.setObjectName(_fromUtf8("label_ConstMinFreq"))
        self.label_ConstDuration = QtGui.QLabel(self.frame_status)
        self.label_ConstDuration.setGeometry(QtCore.QRect(10, 320, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstDuration.setFont(font)
        self.label_ConstDuration.setObjectName(_fromUtf8("label_ConstDuration"))
        self.line_6 = QtGui.QFrame(self.frame_status)
        self.line_6.setGeometry(QtCore.QRect(10, 360, 231, 16))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.label_Duration = QtGui.QLabel(self.frame_status)
        self.label_Duration.setGeometry(QtCore.QRect(10, 340, 231, 17))
        self.label_Duration.setObjectName(_fromUtf8("label_Duration"))
        self.label_ConstFrontLine_1 = QtGui.QLabel(self.frame_status)
        self.label_ConstFrontLine_1.setGeometry(QtCore.QRect(10, 370, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstFrontLine_1.setFont(font)
        self.label_ConstFrontLine_1.setObjectName(_fromUtf8("label_ConstFrontLine_1"))
        self.line_7 = QtGui.QFrame(self.frame_status)
        self.line_7.setGeometry(QtCore.QRect(10, 410, 231, 16))
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.label_FrontLine_1 = QtGui.QLabel(self.frame_status)
        self.label_FrontLine_1.setGeometry(QtCore.QRect(10, 390, 231, 17))
        self.label_FrontLine_1.setObjectName(_fromUtf8("label_FrontLine_1"))
        self.label_ConstFrontLine_2 = QtGui.QLabel(self.frame_status)
        self.label_ConstFrontLine_2.setGeometry(QtCore.QRect(10, 420, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstFrontLine_2.setFont(font)
        self.label_ConstFrontLine_2.setObjectName(_fromUtf8("label_ConstFrontLine_2"))
        self.line_8 = QtGui.QFrame(self.frame_status)
        self.line_8.setGeometry(QtCore.QRect(10, 460, 231, 16))
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.label_FrontLine_2 = QtGui.QLabel(self.frame_status)
        self.label_FrontLine_2.setGeometry(QtCore.QRect(10, 440, 231, 17))
        self.label_FrontLine_2.setObjectName(_fromUtf8("label_FrontLine_2"))
        self.label_ConstFrontLine_3 = QtGui.QLabel(self.frame_status)
        self.label_ConstFrontLine_3.setGeometry(QtCore.QRect(10, 470, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstFrontLine_3.setFont(font)
        self.label_ConstFrontLine_3.setObjectName(_fromUtf8("label_ConstFrontLine_3"))
        self.line_9 = QtGui.QFrame(self.frame_status)
        self.line_9.setGeometry(QtCore.QRect(10, 510, 231, 16))
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.label_FrontLine_3 = QtGui.QLabel(self.frame_status)
        self.label_FrontLine_3.setGeometry(QtCore.QRect(10, 490, 231, 17))
        self.label_FrontLine_3.setObjectName(_fromUtf8("label_FrontLine_3"))
        self.label_ConstFrontLine_4 = QtGui.QLabel(self.frame_status)
        self.label_ConstFrontLine_4.setGeometry(QtCore.QRect(10, 520, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstFrontLine_4.setFont(font)
        self.label_ConstFrontLine_4.setObjectName(_fromUtf8("label_ConstFrontLine_4"))
        self.line_10 = QtGui.QFrame(self.frame_status)
        self.line_10.setGeometry(QtCore.QRect(10, 560, 231, 16))
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.label_FrontLine_4 = QtGui.QLabel(self.frame_status)
        self.label_FrontLine_4.setGeometry(QtCore.QRect(10, 540, 231, 17))
        self.label_FrontLine_4.setObjectName(_fromUtf8("label_FrontLine_4"))
        self.label_ConstFrontLine_5 = QtGui.QLabel(self.frame_status)
        self.label_ConstFrontLine_5.setGeometry(QtCore.QRect(10, 570, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstFrontLine_5.setFont(font)
        self.label_ConstFrontLine_5.setObjectName(_fromUtf8("label_ConstFrontLine_5"))
        self.line_11 = QtGui.QFrame(self.frame_status)
        self.line_11.setGeometry(QtCore.QRect(10, 610, 231, 16))
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.label_FrontLine_5 = QtGui.QLabel(self.frame_status)
        self.label_FrontLine_5.setGeometry(QtCore.QRect(10, 590, 231, 17))
        self.label_FrontLine_5.setObjectName(_fromUtf8("label_FrontLine_5"))
        self.label_ConstFrontLine_6 = QtGui.QLabel(self.frame_status)
        self.label_ConstFrontLine_6.setGeometry(QtCore.QRect(10, 620, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstFrontLine_6.setFont(font)
        self.label_ConstFrontLine_6.setObjectName(_fromUtf8("label_ConstFrontLine_6"))
        self.line_12 = QtGui.QFrame(self.frame_status)
        self.line_12.setGeometry(QtCore.QRect(10, 660, 231, 16))
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.label_FrontLine_6 = QtGui.QLabel(self.frame_status)
        self.label_FrontLine_6.setGeometry(QtCore.QRect(10, 640, 231, 17))
        self.label_FrontLine_6.setObjectName(_fromUtf8("label_FrontLine_6"))
        self.label_ConstFrontLine_7 = QtGui.QLabel(self.frame_status)
        self.label_ConstFrontLine_7.setGeometry(QtCore.QRect(10, 670, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstFrontLine_7.setFont(font)
        self.label_ConstFrontLine_7.setObjectName(_fromUtf8("label_ConstFrontLine_7"))
        self.line_13 = QtGui.QFrame(self.frame_status)
        self.line_13.setGeometry(QtCore.QRect(10, 710, 231, 16))
        self.line_13.setFrameShape(QtGui.QFrame.HLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.label_FrontLine_7 = QtGui.QLabel(self.frame_status)
        self.label_FrontLine_7.setGeometry(QtCore.QRect(10, 690, 231, 17))
        self.label_FrontLine_7.setObjectName(_fromUtf8("label_FrontLine_7"))
        self.label_ConstFrontLine_8 = QtGui.QLabel(self.frame_status)
        self.label_ConstFrontLine_8.setGeometry(QtCore.QRect(10, 720, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstFrontLine_8.setFont(font)
        self.label_ConstFrontLine_8.setObjectName(_fromUtf8("label_ConstFrontLine_8"))
        self.line_14 = QtGui.QFrame(self.frame_status)
        self.line_14.setGeometry(QtCore.QRect(10, 760, 231, 16))
        self.line_14.setFrameShape(QtGui.QFrame.HLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName(_fromUtf8("line_14"))
        self.label_FrontLine_8 = QtGui.QLabel(self.frame_status)
        self.label_FrontLine_8.setGeometry(QtCore.QRect(10, 740, 231, 17))
        self.label_FrontLine_8.setObjectName(_fromUtf8("label_FrontLine_8"))
        self.label_ConstFrontLine_9 = QtGui.QLabel(self.frame_status)
        self.label_ConstFrontLine_9.setGeometry(QtCore.QRect(10, 770, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstFrontLine_9.setFont(font)
        self.label_ConstFrontLine_9.setObjectName(_fromUtf8("label_ConstFrontLine_9"))
        self.line_15 = QtGui.QFrame(self.frame_status)
        self.line_15.setGeometry(QtCore.QRect(10, 810, 231, 16))
        self.line_15.setFrameShape(QtGui.QFrame.HLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName(_fromUtf8("line_15"))
        self.label_FrontLine_9 = QtGui.QLabel(self.frame_status)
        self.label_FrontLine_9.setGeometry(QtCore.QRect(10, 790, 231, 17))
        self.label_FrontLine_9.setObjectName(_fromUtf8("label_FrontLine_9"))
        self.label_ConstFrontLine_10 = QtGui.QLabel(self.frame_status)
        self.label_ConstFrontLine_10.setGeometry(QtCore.QRect(10, 820, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstFrontLine_10.setFont(font)
        self.label_ConstFrontLine_10.setObjectName(_fromUtf8("label_ConstFrontLine_10"))
        self.line_16 = QtGui.QFrame(self.frame_status)
        self.line_16.setGeometry(QtCore.QRect(10, 860, 231, 16))
        self.line_16.setFrameShape(QtGui.QFrame.HLine)
        self.line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_16.setObjectName(_fromUtf8("line_16"))
        self.label_FrontLine_10 = QtGui.QLabel(self.frame_status)
        self.label_FrontLine_10.setGeometry(QtCore.QRect(10, 840, 231, 17))
        self.label_FrontLine_10.setObjectName(_fromUtf8("label_FrontLine_10"))
        self.label_ConstTime = QtGui.QLabel(self.frame_status)
        self.label_ConstTime.setGeometry(QtCore.QRect(10, 160, 66, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstTime.setFont(font)
        self.label_ConstTime.setObjectName(_fromUtf8("label_ConstTime"))
        self.line_19 = QtGui.QFrame(self.frame_status)
        self.line_19.setGeometry(QtCore.QRect(10, 210, 281, 16))
        self.line_19.setFrameShape(QtGui.QFrame.HLine)
        self.line_19.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_19.setObjectName(_fromUtf8("line_19"))
        self.label_time = QtGui.QLabel(self.frame_status)
        self.label_time.setGeometry(QtCore.QRect(10, 180, 231, 17))
        self.label_time.setObjectName(_fromUtf8("label_time"))
        self.frame_eventview = QtGui.QFrame(self.tab_label)
        self.frame_eventview.setGeometry(QtCore.QRect(30, 50, 821, 411))
        self.frame_eventview.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_eventview.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_eventview.setObjectName(_fromUtf8("frame_eventview"))
        self.label_imageshow = QtGui.QLabel(self.frame_eventview)
        self.label_imageshow.setGeometry(QtCore.QRect(10, 10, 791, 421))
        self.label_imageshow.setAlignment(QtCore.Qt.AlignCenter)
        self.label_imageshow.setObjectName(_fromUtf8("label_imageshow"))
        self.frame_BatButtons = QtGui.QFrame(self.tab_label)
        self.frame_BatButtons.setGeometry(QtCore.QRect(60, 560, 751, 331))
        self.frame_BatButtons.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_BatButtons.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_BatButtons.setObjectName(_fromUtf8("frame_BatButtons"))
        self.label_image_pipistrellusNathusii = QtGui.QLabel(self.frame_BatButtons)
        self.label_image_pipistrellusNathusii.setGeometry(QtCore.QRect(20, 170, 141, 91))
        self.label_image_pipistrellusNathusii.setText(_fromUtf8(""))
        self.label_image_pipistrellusNathusii.setPixmap(QtGui.QPixmap(_fromUtf8("Images/PipistrellusNathusii.png")))
        self.label_image_pipistrellusNathusii.setObjectName(_fromUtf8("label_image_pipistrellusNathusii"))
        self.button_noise = QtGui.QPushButton(self.frame_BatButtons)
        self.button_noise.setGeometry(QtCore.QRect(380, 260, 161, 41))
        self.button_noise.setObjectName(_fromUtf8("button_noise"))
        self.label_image_MyotisDasycneme = QtGui.QLabel(self.frame_BatButtons)
        self.label_image_MyotisDasycneme.setGeometry(QtCore.QRect(600, 30, 141, 91))
        self.label_image_MyotisDasycneme.setText(_fromUtf8(""))
        self.label_image_MyotisDasycneme.setPixmap(QtGui.QPixmap(_fromUtf8("Images/MyotisDasycneme.png")))
        self.label_image_MyotisDasycneme.setObjectName(_fromUtf8("label_image_MyotisDasycneme"))
        self.button_MyotisDaubentonii = QtGui.QPushButton(self.frame_BatButtons)
        self.button_MyotisDaubentonii.setGeometry(QtCore.QRect(380, 120, 161, 41))
        self.button_MyotisDaubentonii.setObjectName(_fromUtf8("button_MyotisDaubentonii"))
        self.label_image_PipistrellusPygmaeus = QtGui.QLabel(self.frame_BatButtons)
        self.label_image_PipistrellusPygmaeus.setGeometry(QtCore.QRect(210, 30, 141, 91))
        self.label_image_PipistrellusPygmaeus.setText(_fromUtf8(""))
        self.label_image_PipistrellusPygmaeus.setPixmap(QtGui.QPixmap(_fromUtf8("Images/PipistrellusPygmaeus.png")))
        self.label_image_PipistrellusPygmaeus.setObjectName(_fromUtf8("label_image_PipistrellusPygmaeus"))
        self.label_image_MyotisDaubentonii = QtGui.QLabel(self.frame_BatButtons)
        self.label_image_MyotisDaubentonii.setGeometry(QtCore.QRect(410, 30, 141, 91))
        self.label_image_MyotisDaubentonii.setText(_fromUtf8(""))
        self.label_image_MyotisDaubentonii.setPixmap(QtGui.QPixmap(_fromUtf8("Images/MyotisDaubentonii.png")))
        self.label_image_MyotisDaubentonii.setObjectName(_fromUtf8("label_image_MyotisDaubentonii"))
        self.button_pipistrellusNathusii = QtGui.QPushButton(self.frame_BatButtons)
        self.button_pipistrellusNathusii.setGeometry(QtCore.QRect(0, 260, 151, 41))
        self.button_pipistrellusNathusii.setObjectName(_fromUtf8("button_pipistrellusNathusii"))
        self.label_image_NyctalusNoctula = QtGui.QLabel(self.frame_BatButtons)
        self.label_image_NyctalusNoctula.setGeometry(QtCore.QRect(210, 170, 141, 91))
        self.label_image_NyctalusNoctula.setText(_fromUtf8(""))
        self.label_image_NyctalusNoctula.setPixmap(QtGui.QPixmap(_fromUtf8("Images/NyctalusNoctula.png")))
        self.label_image_NyctalusNoctula.setObjectName(_fromUtf8("label_image_NyctalusNoctula"))
        self.label_image_EptesicusSerptinus = QtGui.QLabel(self.frame_BatButtons)
        self.label_image_EptesicusSerptinus.setGeometry(QtCore.QRect(20, 26, 141, 91))
        self.label_image_EptesicusSerptinus.setText(_fromUtf8(""))
        self.label_image_EptesicusSerptinus.setPixmap(QtGui.QPixmap(_fromUtf8("Images/EptesicusSerotinus.png")))
        self.label_image_EptesicusSerptinus.setObjectName(_fromUtf8("label_image_EptesicusSerptinus"))
        self.button_NyctalusNoctula = QtGui.QPushButton(self.frame_BatButtons)
        self.button_NyctalusNoctula.setGeometry(QtCore.QRect(180, 260, 171, 41))
        self.button_NyctalusNoctula.setObjectName(_fromUtf8("button_NyctalusNoctula"))
        self.button_MyotisDasycneme = QtGui.QPushButton(self.frame_BatButtons)
        self.button_MyotisDasycneme.setGeometry(QtCore.QRect(570, 120, 161, 41))
        self.button_MyotisDasycneme.setObjectName(_fromUtf8("button_MyotisDasycneme"))
        self.button_EptesicusSerotinus = QtGui.QPushButton(self.frame_BatButtons)
        self.button_EptesicusSerotinus.setGeometry(QtCore.QRect(0, 120, 161, 41))
        self.button_EptesicusSerotinus.setObjectName(_fromUtf8("button_EptesicusSerotinus"))
        self.button_PipistrellusPygmaeus = QtGui.QPushButton(self.frame_BatButtons)
        self.button_PipistrellusPygmaeus.setGeometry(QtCore.QRect(180, 120, 181, 41))
        self.button_PipistrellusPygmaeus.setObjectName(_fromUtf8("button_PipistrellusPygmaeus"))
        self.button_OtherSpecies = QtGui.QPushButton(self.frame_BatButtons)
        self.button_OtherSpecies.setGeometry(QtCore.QRect(577, 260, 151, 41))
        self.button_OtherSpecies.setObjectName(_fromUtf8("button_OtherSpecies"))
        self.progressBar_eventLabel = QtGui.QProgressBar(self.tab_label)
        self.progressBar_eventLabel.setGeometry(QtCore.QRect(27, 530, 821, 23))
        self.progressBar_eventLabel.setProperty("value", 0)
        self.progressBar_eventLabel.setObjectName(_fromUtf8("progressBar_eventLabel"))
        self.label_currentStatus = QtGui.QLabel(self.tab_label)
        self.label_currentStatus.setGeometry(QtCore.QRect(30, 510, 621, 17))
        self.label_currentStatus.setObjectName(_fromUtf8("label_currentStatus"))
        self.checkBox_scaledZoom = QtGui.QCheckBox(self.tab_label)
        self.checkBox_scaledZoom.setGeometry(QtCore.QRect(710, 470, 131, 22))
        self.checkBox_scaledZoom.setChecked(True)
        self.checkBox_scaledZoom.setObjectName(_fromUtf8("checkBox_scaledZoom"))
        self.button_ShowFullSpectrogram = QtGui.QPushButton(self.tab_label)
        self.button_ShowFullSpectrogram.setGeometry(QtCore.QRect(30, 460, 231, 41))
        self.button_ShowFullSpectrogram.setObjectName(_fromUtf8("button_ShowFullSpectrogram"))
        self.button_ShowMarkedSpectrogram = QtGui.QPushButton(self.tab_label)
        self.button_ShowMarkedSpectrogram.setGeometry(QtCore.QRect(270, 460, 231, 41))
        self.button_ShowMarkedSpectrogram.setObjectName(_fromUtf8("button_ShowMarkedSpectrogram"))
        self.tabWidget.addTab(self.tab_label, _fromUtf8(""))
        BatWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(BatWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(BatWindow)

    def retranslateUi(self, BatWindow):
        BatWindow.setWindowTitle(_translate("BatWindow", "Bat GUI Analyzer", None))
        self.button_start.setText(_translate("BatWindow", "Start Analyzing", None))
        self.label_status.setText(_translate("BatWindow", "Status", None))
        self.pushButton_createSpectrogram.setText(_translate("BatWindow", "Create Spectrogram", None))
        self.pushButton_SetInputDirectory.setWhatsThis(_translate("BatWindow", "Select the directory containing the .s16 files", None))
        self.pushButton_SetInputDirectory.setText(_translate("BatWindow", "Select Input Directory", None))
        self.pushButton_SetOutputDirectory.setWhatsThis(_translate("BatWindow", "Select the output directory where all the generated files will be saved to", None))
        self.pushButton_SetOutputDirectory.setText(_translate("BatWindow", "Select Output Directory", None))
        self.label_inputDirectory.setText(_translate("BatWindow", "/home/anoch/Documents/BatSamples", None))
        self.label_outputDirectory.setText(_translate("BatWindow", "/home/anoch/Documents/BatSamples", None))
        self.label_Channel.setText(_translate("BatWindow", "Select Channel:", None))
        self.radioButton_channel_1.setText(_translate("BatWindow", "Channel 1", None))
        self.radioButton_channel_2.setText(_translate("BatWindow", "Channel 2", None))
        self.radioButton_channel_3.setText(_translate("BatWindow", "Channel 3", None))
        self.radioButton_channel_4.setText(_translate("BatWindow", "Channel 4", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_analyze), _translate("BatWindow", "Analyze", None))
        self.button_loaddatabase.setText(_translate("BatWindow", "Load Database", None))
        self.label_database_name.setText(_translate("BatWindow", "No Database Selected", None))
        self.label_ConstEventName.setText(_translate("BatWindow", "Event Name:", None))
        self.label_ConstEventNo.setText(_translate("BatWindow", "Event no.:", None))
        self.label_ConstDate.setText(_translate("BatWindow", "Date:", None))
        self.label_EventName.setText(_translate("BatWindow", "N/A", None))
        self.label_EventNo.setText(_translate("BatWindow", "N/A", None))
        self.label_Date.setText(_translate("BatWindow", "N/A", None))
        self.label_maxFreq.setText(_translate("BatWindow", "N/A", None))
        self.label_ConstMaxFreq.setText(_translate("BatWindow", "Max Frequency [kHz]:", None))
        self.label_MinFreq.setText(_translate("BatWindow", "N/A", None))
        self.label_ConstMinFreq.setText(_translate("BatWindow", "Min Frequency [kHz]:", None))
        self.label_ConstDuration.setText(_translate("BatWindow", "Duration [ms]:", None))
        self.label_Duration.setText(_translate("BatWindow", "N/A", None))
        self.label_ConstFrontLine_1.setText(_translate("BatWindow", "Front Line 1:", None))
        self.label_FrontLine_1.setText(_translate("BatWindow", "N/A", None))
        self.label_ConstFrontLine_2.setText(_translate("BatWindow", "Front Line 2:", None))
        self.label_FrontLine_2.setText(_translate("BatWindow", "N/A", None))
        self.label_ConstFrontLine_3.setText(_translate("BatWindow", "Front Line 3:", None))
        self.label_FrontLine_3.setText(_translate("BatWindow", "N/A", None))
        self.label_ConstFrontLine_4.setText(_translate("BatWindow", "Front Line 4:", None))
        self.label_FrontLine_4.setText(_translate("BatWindow", "N/A", None))
        self.label_ConstFrontLine_5.setText(_translate("BatWindow", "Front Line 5:", None))
        self.label_FrontLine_5.setText(_translate("BatWindow", "N/A", None))
        self.label_ConstFrontLine_6.setText(_translate("BatWindow", "Front Line 6:", None))
        self.label_FrontLine_6.setText(_translate("BatWindow", "N/A", None))
        self.label_ConstFrontLine_7.setText(_translate("BatWindow", "Front Line 7:", None))
        self.label_FrontLine_7.setText(_translate("BatWindow", "N/A", None))
        self.label_ConstFrontLine_8.setText(_translate("BatWindow", "Front Line 8:", None))
        self.label_FrontLine_8.setText(_translate("BatWindow", "N/A", None))
        self.label_ConstFrontLine_9.setText(_translate("BatWindow", "Front Line 9:", None))
        self.label_FrontLine_9.setText(_translate("BatWindow", "N/A", None))
        self.label_ConstFrontLine_10.setText(_translate("BatWindow", "Front Line 10:", None))
        self.label_FrontLine_10.setText(_translate("BatWindow", "N/A", None))
        self.label_ConstTime.setText(_translate("BatWindow", "Time:", None))
        self.label_time.setText(_translate("BatWindow", "N/A", None))
        self.label_imageshow.setText(_translate("BatWindow", "Event Viewer", None))
        self.button_noise.setText(_translate("BatWindow", "(7) Noise", None))
        self.button_MyotisDaubentonii.setText(_translate("BatWindow", "(3) Myotis daubentonii", None))
        self.button_pipistrellusNathusii.setText(_translate("BatWindow", "(5) Pipistrellus nathusii", None))
        self.button_NyctalusNoctula.setText(_translate("BatWindow", "(6) Nyctalus noctula", None))
        self.button_MyotisDasycneme.setText(_translate("BatWindow", "(4) Myotis dasycneme", None))
        self.button_EptesicusSerotinus.setText(_translate("BatWindow", "(1) Eptesicus serotinus", None))
        self.button_PipistrellusPygmaeus.setText(_translate("BatWindow", "(2) Pipistrellus pygmaeus", None))
        self.button_OtherSpecies.setText(_translate("BatWindow", "(8) Other Species", None))
        self.label_currentStatus.setText(_translate("BatWindow", "N/A", None))
        self.checkBox_scaledZoom.setText(_translate("BatWindow", "Fit To Screen (z)", None))
        self.button_ShowFullSpectrogram.setText(_translate("BatWindow", "Show Full Spectrogram (s)", None))
        self.button_ShowMarkedSpectrogram.setText(_translate("BatWindow", "Show Marked Spectrogram (m)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_label), _translate("BatWindow", "Label Events", None))

