# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BatWindow.ui'
#
# Created: Thu Mar 12 10:35:44 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_BatWindow(object):
    def setupUi(self, BatWindow):
        BatWindow.setObjectName(_fromUtf8("BatWindow"))
        BatWindow.resize(1225, 975)
        self.centralwidget = QtGui.QWidget(BatWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1201, 961))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_analyze = QtGui.QWidget()
        self.tab_analyze.setObjectName(_fromUtf8("tab_analyze"))
        self.button_start = QtGui.QPushButton(self.tab_analyze)
        self.button_start.setGeometry(QtCore.QRect(765, 700, 181, 51))
        self.button_start.setObjectName(_fromUtf8("button_start"))
        self.progressBar_analyse = QtGui.QProgressBar(self.tab_analyze)
        self.progressBar_analyse.setGeometry(QtCore.QRect(95, 440, 991, 23))
        self.progressBar_analyse.setProperty("value", 0)
        self.progressBar_analyse.setObjectName(_fromUtf8("progressBar_analyse"))
        self.textEdit_overview = QtGui.QTextEdit(self.tab_analyze)
        self.textEdit_overview.setGeometry(QtCore.QRect(95, 50, 991, 371))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_overview.setFont(font)
        self.textEdit_overview.setLineWrapMode(QtGui.QTextEdit.WidgetWidth)
        self.textEdit_overview.setReadOnly(True)
        self.textEdit_overview.setObjectName(_fromUtf8("textEdit_overview"))
        self.label_status = QtGui.QLabel(self.tab_analyze)
        self.label_status.setGeometry(QtCore.QRect(95, 30, 66, 17))
        self.label_status.setObjectName(_fromUtf8("label_status"))
        self.pushButton_createSpectrogram = QtGui.QPushButton(self.tab_analyze)
        self.pushButton_createSpectrogram.setGeometry(QtCore.QRect(170, 700, 181, 51))
        self.pushButton_createSpectrogram.setObjectName(_fromUtf8("pushButton_createSpectrogram"))
        self.pushButton_SetInputDirectory = QtGui.QPushButton(self.tab_analyze)
        self.pushButton_SetInputDirectory.setGeometry(QtCore.QRect(105, 490, 171, 31))
        self.pushButton_SetInputDirectory.setObjectName(_fromUtf8("pushButton_SetInputDirectory"))
        self.pushButton_SetOutputDirectory = QtGui.QPushButton(self.tab_analyze)
        self.pushButton_SetOutputDirectory.setGeometry(QtCore.QRect(105, 570, 171, 31))
        self.pushButton_SetOutputDirectory.setObjectName(_fromUtf8("pushButton_SetOutputDirectory"))
        self.label_inputDirectory = QtGui.QLabel(self.tab_analyze)
        self.label_inputDirectory.setGeometry(QtCore.QRect(105, 530, 811, 20))
        self.label_inputDirectory.setObjectName(_fromUtf8("label_inputDirectory"))
        self.line_17 = QtGui.QFrame(self.tab_analyze)
        self.line_17.setGeometry(QtCore.QRect(15, 550, 1161, 20))
        self.line_17.setFrameShape(QtGui.QFrame.HLine)
        self.line_17.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_17.setObjectName(_fromUtf8("line_17"))
        self.label_outputDirectory = QtGui.QLabel(self.tab_analyze)
        self.label_outputDirectory.setGeometry(QtCore.QRect(105, 610, 811, 20))
        self.label_outputDirectory.setObjectName(_fromUtf8("label_outputDirectory"))
        self.line_18 = QtGui.QFrame(self.tab_analyze)
        self.line_18.setGeometry(QtCore.QRect(15, 630, 1161, 20))
        self.line_18.setFrameShape(QtGui.QFrame.HLine)
        self.line_18.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_18.setObjectName(_fromUtf8("line_18"))
        self.label_Channel = QtGui.QLabel(self.tab_analyze)
        self.label_Channel.setGeometry(QtCore.QRect(25, 770, 111, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_Channel.setFont(font)
        self.label_Channel.setObjectName(_fromUtf8("label_Channel"))
        self.frame_rbChannel = QtGui.QFrame(self.tab_analyze)
        self.frame_rbChannel.setGeometry(QtCore.QRect(170, 760, 181, 131))
        self.frame_rbChannel.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_rbChannel.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_rbChannel.setObjectName(_fromUtf8("frame_rbChannel"))
        self.radioButton_channel_1 = QtGui.QRadioButton(self.frame_rbChannel)
        self.radioButton_channel_1.setGeometry(QtCore.QRect(10, 10, 116, 22))
        self.radioButton_channel_1.setChecked(True)
        self.radioButton_channel_1.setObjectName(_fromUtf8("radioButton_channel_1"))
        self.radioButton_channel_2 = QtGui.QRadioButton(self.frame_rbChannel)
        self.radioButton_channel_2.setGeometry(QtCore.QRect(10, 40, 116, 22))
        self.radioButton_channel_2.setObjectName(_fromUtf8("radioButton_channel_2"))
        self.radioButton_channel_3 = QtGui.QRadioButton(self.frame_rbChannel)
        self.radioButton_channel_3.setGeometry(QtCore.QRect(10, 70, 116, 22))
        self.radioButton_channel_3.setObjectName(_fromUtf8("radioButton_channel_3"))
        self.radioButton_channel_4 = QtGui.QRadioButton(self.frame_rbChannel)
        self.radioButton_channel_4.setGeometry(QtCore.QRect(10, 100, 116, 22))
        self.radioButton_channel_4.setObjectName(_fromUtf8("radioButton_channel_4"))
        self.tabWidget.addTab(self.tab_analyze, _fromUtf8(""))
        self.tab_label_species = QtGui.QWidget()
        self.tab_label_species.setObjectName(_fromUtf8("tab_label_species"))
        self.button_loaddatabase = QtGui.QPushButton(self.tab_label_species)
        self.button_loaddatabase.setGeometry(QtCore.QRect(30, 10, 131, 41))
        self.button_loaddatabase.setObjectName(_fromUtf8("button_loaddatabase"))
        self.label_database_name = QtGui.QLabel(self.tab_label_species)
        self.label_database_name.setGeometry(QtCore.QRect(170, 20, 611, 17))
        self.label_database_name.setObjectName(_fromUtf8("label_database_name"))
        self.frame_status = QtGui.QFrame(self.tab_label_species)
        self.frame_status.setGeometry(QtCore.QRect(870, 10, 301, 911))
        self.frame_status.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_status.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_status.setObjectName(_fromUtf8("frame_status"))
        self.label_ConstEventName = QtGui.QLabel(self.frame_status)
        self.label_ConstEventName.setGeometry(QtCore.QRect(10, 10, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstEventName.setFont(font)
        self.label_ConstEventName.setObjectName(_fromUtf8("label_ConstEventName"))
        self.line = QtGui.QFrame(self.frame_status)
        self.line.setGeometry(QtCore.QRect(10, 50, 281, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_ConstEventNo = QtGui.QLabel(self.frame_status)
        self.label_ConstEventNo.setGeometry(QtCore.QRect(10, 60, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstEventNo.setFont(font)
        self.label_ConstEventNo.setObjectName(_fromUtf8("label_ConstEventNo"))
        self.line_2 = QtGui.QFrame(self.frame_status)
        self.line_2.setGeometry(QtCore.QRect(10, 100, 231, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label_ConstDate = QtGui.QLabel(self.frame_status)
        self.label_ConstDate.setGeometry(QtCore.QRect(10, 110, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstDate.setFont(font)
        self.label_ConstDate.setObjectName(_fromUtf8("label_ConstDate"))
        self.line_3 = QtGui.QFrame(self.frame_status)
        self.line_3.setGeometry(QtCore.QRect(10, 150, 231, 16))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.label_EventName = QtGui.QLabel(self.frame_status)
        self.label_EventName.setGeometry(QtCore.QRect(10, 30, 281, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_EventName.setFont(font)
        self.label_EventName.setObjectName(_fromUtf8("label_EventName"))
        self.label_EventNo = QtGui.QLabel(self.frame_status)
        self.label_EventNo.setGeometry(QtCore.QRect(10, 80, 231, 17))
        self.label_EventNo.setObjectName(_fromUtf8("label_EventNo"))
        self.label_Date = QtGui.QLabel(self.frame_status)
        self.label_Date.setGeometry(QtCore.QRect(10, 130, 231, 17))
        self.label_Date.setObjectName(_fromUtf8("label_Date"))
        self.line_4 = QtGui.QFrame(self.frame_status)
        self.line_4.setGeometry(QtCore.QRect(10, 300, 231, 16))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.label_maxFreq = QtGui.QLabel(self.frame_status)
        self.label_maxFreq.setGeometry(QtCore.QRect(10, 230, 231, 17))
        self.label_maxFreq.setObjectName(_fromUtf8("label_maxFreq"))
        self.label_ConstMaxFreq = QtGui.QLabel(self.frame_status)
        self.label_ConstMaxFreq.setGeometry(QtCore.QRect(10, 210, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstMaxFreq.setFont(font)
        self.label_ConstMaxFreq.setObjectName(_fromUtf8("label_ConstMaxFreq"))
        self.label_MinFreq = QtGui.QLabel(self.frame_status)
        self.label_MinFreq.setGeometry(QtCore.QRect(10, 280, 231, 17))
        self.label_MinFreq.setObjectName(_fromUtf8("label_MinFreq"))
        self.line_5 = QtGui.QFrame(self.frame_status)
        self.line_5.setGeometry(QtCore.QRect(10, 240, 231, 16))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.label_ConstMinFreq = QtGui.QLabel(self.frame_status)
        self.label_ConstMinFreq.setGeometry(QtCore.QRect(10, 260, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstMinFreq.setFont(font)
        self.label_ConstMinFreq.setObjectName(_fromUtf8("label_ConstMinFreq"))
        self.label_ConstDuration = QtGui.QLabel(self.frame_status)
        self.label_ConstDuration.setGeometry(QtCore.QRect(10, 310, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstDuration.setFont(font)
        self.label_ConstDuration.setObjectName(_fromUtf8("label_ConstDuration"))
        self.line_6 = QtGui.QFrame(self.frame_status)
        self.line_6.setGeometry(QtCore.QRect(10, 350, 231, 16))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.label_Duration = QtGui.QLabel(self.frame_status)
        self.label_Duration.setGeometry(QtCore.QRect(10, 330, 231, 17))
        self.label_Duration.setObjectName(_fromUtf8("label_Duration"))
        self.label_ConstFrontLine_1 = QtGui.QLabel(self.frame_status)
        self.label_ConstFrontLine_1.setGeometry(QtCore.QRect(10, 360, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstFrontLine_1.setFont(font)
        self.label_ConstFrontLine_1.setObjectName(_fromUtf8("label_ConstFrontLine_1"))
        self.line_7 = QtGui.QFrame(self.frame_status)
        self.line_7.setGeometry(QtCore.QRect(10, 400, 231, 16))
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.label_FrontLine_1 = QtGui.QLabel(self.frame_status)
        self.label_FrontLine_1.setGeometry(QtCore.QRect(10, 380, 231, 17))
        self.label_FrontLine_1.setObjectName(_fromUtf8("label_FrontLine_1"))
        self.label_ConstFrontLine_2 = QtGui.QLabel(self.frame_status)
        self.label_ConstFrontLine_2.setGeometry(QtCore.QRect(10, 410, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstFrontLine_2.setFont(font)
        self.label_ConstFrontLine_2.setObjectName(_fromUtf8("label_ConstFrontLine_2"))
        self.line_8 = QtGui.QFrame(self.frame_status)
        self.line_8.setGeometry(QtCore.QRect(10, 450, 231, 16))
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.label_FrontLine_2 = QtGui.QLabel(self.frame_status)
        self.label_FrontLine_2.setGeometry(QtCore.QRect(10, 430, 231, 17))
        self.label_FrontLine_2.setObjectName(_fromUtf8("label_FrontLine_2"))
        self.label_ConstFrontLine_3 = QtGui.QLabel(self.frame_status)
        self.label_ConstFrontLine_3.setGeometry(QtCore.QRect(10, 460, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstFrontLine_3.setFont(font)
        self.label_ConstFrontLine_3.setObjectName(_fromUtf8("label_ConstFrontLine_3"))
        self.line_9 = QtGui.QFrame(self.frame_status)
        self.line_9.setGeometry(QtCore.QRect(10, 500, 231, 16))
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.label_FrontLine_3 = QtGui.QLabel(self.frame_status)
        self.label_FrontLine_3.setGeometry(QtCore.QRect(10, 480, 231, 17))
        self.label_FrontLine_3.setObjectName(_fromUtf8("label_FrontLine_3"))
        self.label_ConstFrontLine_4 = QtGui.QLabel(self.frame_status)
        self.label_ConstFrontLine_4.setGeometry(QtCore.QRect(10, 510, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstFrontLine_4.setFont(font)
        self.label_ConstFrontLine_4.setObjectName(_fromUtf8("label_ConstFrontLine_4"))
        self.line_10 = QtGui.QFrame(self.frame_status)
        self.line_10.setGeometry(QtCore.QRect(10, 550, 231, 16))
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.label_FrontLine_4 = QtGui.QLabel(self.frame_status)
        self.label_FrontLine_4.setGeometry(QtCore.QRect(10, 530, 231, 17))
        self.label_FrontLine_4.setObjectName(_fromUtf8("label_FrontLine_4"))
        self.label_ConstFrontLine_5 = QtGui.QLabel(self.frame_status)
        self.label_ConstFrontLine_5.setGeometry(QtCore.QRect(10, 560, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstFrontLine_5.setFont(font)
        self.label_ConstFrontLine_5.setObjectName(_fromUtf8("label_ConstFrontLine_5"))
        self.line_11 = QtGui.QFrame(self.frame_status)
        self.line_11.setGeometry(QtCore.QRect(10, 610, 231, 16))
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.label_FrontLine_5 = QtGui.QLabel(self.frame_status)
        self.label_FrontLine_5.setGeometry(QtCore.QRect(10, 580, 231, 17))
        self.label_FrontLine_5.setObjectName(_fromUtf8("label_FrontLine_5"))
        self.label_ConstFrontLine_6 = QtGui.QLabel(self.frame_status)
        self.label_ConstFrontLine_6.setGeometry(QtCore.QRect(10, 610, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstFrontLine_6.setFont(font)
        self.label_ConstFrontLine_6.setObjectName(_fromUtf8("label_ConstFrontLine_6"))
        self.line_12 = QtGui.QFrame(self.frame_status)
        self.line_12.setGeometry(QtCore.QRect(10, 650, 231, 16))
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.label_FrontLine_6 = QtGui.QLabel(self.frame_status)
        self.label_FrontLine_6.setGeometry(QtCore.QRect(10, 630, 231, 17))
        self.label_FrontLine_6.setObjectName(_fromUtf8("label_FrontLine_6"))
        self.label_ConstFrontLine_7 = QtGui.QLabel(self.frame_status)
        self.label_ConstFrontLine_7.setGeometry(QtCore.QRect(10, 660, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstFrontLine_7.setFont(font)
        self.label_ConstFrontLine_7.setObjectName(_fromUtf8("label_ConstFrontLine_7"))
        self.line_13 = QtGui.QFrame(self.frame_status)
        self.line_13.setGeometry(QtCore.QRect(10, 700, 231, 16))
        self.line_13.setFrameShape(QtGui.QFrame.HLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.label_FrontLine_7 = QtGui.QLabel(self.frame_status)
        self.label_FrontLine_7.setGeometry(QtCore.QRect(10, 680, 231, 17))
        self.label_FrontLine_7.setObjectName(_fromUtf8("label_FrontLine_7"))
        self.label_ConstFrontLine_8 = QtGui.QLabel(self.frame_status)
        self.label_ConstFrontLine_8.setGeometry(QtCore.QRect(10, 710, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstFrontLine_8.setFont(font)
        self.label_ConstFrontLine_8.setObjectName(_fromUtf8("label_ConstFrontLine_8"))
        self.line_14 = QtGui.QFrame(self.frame_status)
        self.line_14.setGeometry(QtCore.QRect(10, 750, 231, 16))
        self.line_14.setFrameShape(QtGui.QFrame.HLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName(_fromUtf8("line_14"))
        self.label_FrontLine_8 = QtGui.QLabel(self.frame_status)
        self.label_FrontLine_8.setGeometry(QtCore.QRect(10, 730, 231, 17))
        self.label_FrontLine_8.setObjectName(_fromUtf8("label_FrontLine_8"))
        self.label_ConstFrontLine_9 = QtGui.QLabel(self.frame_status)
        self.label_ConstFrontLine_9.setGeometry(QtCore.QRect(10, 760, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstFrontLine_9.setFont(font)
        self.label_ConstFrontLine_9.setObjectName(_fromUtf8("label_ConstFrontLine_9"))
        self.line_15 = QtGui.QFrame(self.frame_status)
        self.line_15.setGeometry(QtCore.QRect(10, 800, 231, 16))
        self.line_15.setFrameShape(QtGui.QFrame.HLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName(_fromUtf8("line_15"))
        self.label_FrontLine_9 = QtGui.QLabel(self.frame_status)
        self.label_FrontLine_9.setGeometry(QtCore.QRect(10, 780, 231, 17))
        self.label_FrontLine_9.setObjectName(_fromUtf8("label_FrontLine_9"))
        self.label_ConstFrontLine_10 = QtGui.QLabel(self.frame_status)
        self.label_ConstFrontLine_10.setGeometry(QtCore.QRect(10, 810, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstFrontLine_10.setFont(font)
        self.label_ConstFrontLine_10.setObjectName(_fromUtf8("label_ConstFrontLine_10"))
        self.line_16 = QtGui.QFrame(self.frame_status)
        self.line_16.setGeometry(QtCore.QRect(10, 850, 231, 16))
        self.line_16.setFrameShape(QtGui.QFrame.HLine)
        self.line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_16.setObjectName(_fromUtf8("line_16"))
        self.label_FrontLine_10 = QtGui.QLabel(self.frame_status)
        self.label_FrontLine_10.setGeometry(QtCore.QRect(10, 830, 231, 17))
        self.label_FrontLine_10.setObjectName(_fromUtf8("label_FrontLine_10"))
        self.label_ConstTime = QtGui.QLabel(self.frame_status)
        self.label_ConstTime.setGeometry(QtCore.QRect(10, 160, 66, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstTime.setFont(font)
        self.label_ConstTime.setObjectName(_fromUtf8("label_ConstTime"))
        self.line_19 = QtGui.QFrame(self.frame_status)
        self.line_19.setGeometry(QtCore.QRect(10, 200, 231, 16))
        self.line_19.setFrameShape(QtGui.QFrame.HLine)
        self.line_19.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_19.setObjectName(_fromUtf8("line_19"))
        self.label_time = QtGui.QLabel(self.frame_status)
        self.label_time.setGeometry(QtCore.QRect(10, 180, 231, 17))
        self.label_time.setObjectName(_fromUtf8("label_time"))
        self.label_ConstFrontLine_11 = QtGui.QLabel(self.frame_status)
        self.label_ConstFrontLine_11.setGeometry(QtCore.QRect(10, 860, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstFrontLine_11.setFont(font)
        self.label_ConstFrontLine_11.setObjectName(_fromUtf8("label_ConstFrontLine_11"))
        self.label_FrontLine_11 = QtGui.QLabel(self.frame_status)
        self.label_FrontLine_11.setGeometry(QtCore.QRect(10, 880, 231, 17))
        self.label_FrontLine_11.setObjectName(_fromUtf8("label_FrontLine_11"))
        self.line_21 = QtGui.QFrame(self.frame_status)
        self.line_21.setGeometry(QtCore.QRect(10, 900, 231, 16))
        self.line_21.setFrameShape(QtGui.QFrame.HLine)
        self.line_21.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_21.setObjectName(_fromUtf8("line_21"))
        self.frame_eventview = QtGui.QFrame(self.tab_label_species)
        self.frame_eventview.setGeometry(QtCore.QRect(30, 50, 821, 411))
        self.frame_eventview.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_eventview.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_eventview.setObjectName(_fromUtf8("frame_eventview"))
        self.label_imageshow = QtGui.QLabel(self.frame_eventview)
        self.label_imageshow.setGeometry(QtCore.QRect(10, 10, 791, 421))
        self.label_imageshow.setAlignment(QtCore.Qt.AlignCenter)
        self.label_imageshow.setObjectName(_fromUtf8("label_imageshow"))
        self.frame_BatButtons = QtGui.QFrame(self.tab_label_species)
        self.frame_BatButtons.setGeometry(QtCore.QRect(60, 560, 751, 331))
        self.frame_BatButtons.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_BatButtons.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_BatButtons.setObjectName(_fromUtf8("frame_BatButtons"))
        self.label_image_pipistrellusNathusii = QtGui.QLabel(self.frame_BatButtons)
        self.label_image_pipistrellusNathusii.setGeometry(QtCore.QRect(20, 170, 141, 91))
        self.label_image_pipistrellusNathusii.setText(_fromUtf8(""))
        self.label_image_pipistrellusNathusii.setPixmap(QtGui.QPixmap(_fromUtf8("Images/PipistrellusNathusii.png")))
        self.label_image_pipistrellusNathusii.setObjectName(_fromUtf8("label_image_pipistrellusNathusii"))
        self.button_noise = QtGui.QPushButton(self.frame_BatButtons)
        self.button_noise.setGeometry(QtCore.QRect(380, 190, 161, 41))
        self.button_noise.setObjectName(_fromUtf8("button_noise"))
        self.label_image_MyotisDasycneme = QtGui.QLabel(self.frame_BatButtons)
        self.label_image_MyotisDasycneme.setGeometry(QtCore.QRect(600, 30, 141, 91))
        self.label_image_MyotisDasycneme.setText(_fromUtf8(""))
        self.label_image_MyotisDasycneme.setPixmap(QtGui.QPixmap(_fromUtf8("Images/MyotisDasycneme.png")))
        self.label_image_MyotisDasycneme.setObjectName(_fromUtf8("label_image_MyotisDasycneme"))
        self.button_MyotisDaubentonii = QtGui.QPushButton(self.frame_BatButtons)
        self.button_MyotisDaubentonii.setGeometry(QtCore.QRect(380, 120, 161, 41))
        self.button_MyotisDaubentonii.setObjectName(_fromUtf8("button_MyotisDaubentonii"))
        self.label_image_PipistrellusPygmaeus = QtGui.QLabel(self.frame_BatButtons)
        self.label_image_PipistrellusPygmaeus.setGeometry(QtCore.QRect(210, 30, 141, 91))
        self.label_image_PipistrellusPygmaeus.setText(_fromUtf8(""))
        self.label_image_PipistrellusPygmaeus.setPixmap(QtGui.QPixmap(_fromUtf8("Images/PipistrellusPygmaeus.png")))
        self.label_image_PipistrellusPygmaeus.setObjectName(_fromUtf8("label_image_PipistrellusPygmaeus"))
        self.label_image_MyotisDaubentonii = QtGui.QLabel(self.frame_BatButtons)
        self.label_image_MyotisDaubentonii.setGeometry(QtCore.QRect(410, 30, 141, 91))
        self.label_image_MyotisDaubentonii.setText(_fromUtf8(""))
        self.label_image_MyotisDaubentonii.setPixmap(QtGui.QPixmap(_fromUtf8("Images/MyotisDaubentonii.png")))
        self.label_image_MyotisDaubentonii.setObjectName(_fromUtf8("label_image_MyotisDaubentonii"))
        self.button_pipistrellusNathusii = QtGui.QPushButton(self.frame_BatButtons)
        self.button_pipistrellusNathusii.setGeometry(QtCore.QRect(0, 260, 151, 41))
        self.button_pipistrellusNathusii.setObjectName(_fromUtf8("button_pipistrellusNathusii"))
        self.label_image_NyctalusNoctula = QtGui.QLabel(self.frame_BatButtons)
        self.label_image_NyctalusNoctula.setGeometry(QtCore.QRect(210, 170, 141, 91))
        self.label_image_NyctalusNoctula.setText(_fromUtf8(""))
        self.label_image_NyctalusNoctula.setPixmap(QtGui.QPixmap(_fromUtf8("Images/NyctalusNoctula.png")))
        self.label_image_NyctalusNoctula.setObjectName(_fromUtf8("label_image_NyctalusNoctula"))
        self.label_image_EptesicusSerptinus = QtGui.QLabel(self.frame_BatButtons)
        self.label_image_EptesicusSerptinus.setGeometry(QtCore.QRect(20, 26, 141, 91))
        self.label_image_EptesicusSerptinus.setText(_fromUtf8(""))
        self.label_image_EptesicusSerptinus.setPixmap(QtGui.QPixmap(_fromUtf8("Images/EptesicusSerotinus.png")))
        self.label_image_EptesicusSerptinus.setObjectName(_fromUtf8("label_image_EptesicusSerptinus"))
        self.button_NyctalusNoctula = QtGui.QPushButton(self.frame_BatButtons)
        self.button_NyctalusNoctula.setGeometry(QtCore.QRect(180, 260, 171, 41))
        self.button_NyctalusNoctula.setObjectName(_fromUtf8("button_NyctalusNoctula"))
        self.button_MyotisDasycneme = QtGui.QPushButton(self.frame_BatButtons)
        self.button_MyotisDasycneme.setGeometry(QtCore.QRect(570, 120, 161, 41))
        self.button_MyotisDasycneme.setObjectName(_fromUtf8("button_MyotisDasycneme"))
        self.button_EptesicusSerotinus = QtGui.QPushButton(self.frame_BatButtons)
        self.button_EptesicusSerotinus.setGeometry(QtCore.QRect(0, 120, 161, 41))
        self.button_EptesicusSerotinus.setObjectName(_fromUtf8("button_EptesicusSerotinus"))
        self.button_PipistrellusPygmaeus = QtGui.QPushButton(self.frame_BatButtons)
        self.button_PipistrellusPygmaeus.setGeometry(QtCore.QRect(180, 120, 181, 41))
        self.button_PipistrellusPygmaeus.setObjectName(_fromUtf8("button_PipistrellusPygmaeus"))
        self.button_OtherSpecies = QtGui.QPushButton(self.frame_BatButtons)
        self.button_OtherSpecies.setGeometry(QtCore.QRect(380, 260, 161, 41))
        self.button_OtherSpecies.setObjectName(_fromUtf8("button_OtherSpecies"))
        self.button_SomethingElse = QtGui.QPushButton(self.frame_BatButtons)
        self.button_SomethingElse.setGeometry(QtCore.QRect(570, 190, 161, 41))
        self.button_SomethingElse.setObjectName(_fromUtf8("button_SomethingElse"))
        self.progressBar_eventLabel = QtGui.QProgressBar(self.tab_label_species)
        self.progressBar_eventLabel.setGeometry(QtCore.QRect(27, 530, 821, 23))
        self.progressBar_eventLabel.setProperty("value", 0)
        self.progressBar_eventLabel.setObjectName(_fromUtf8("progressBar_eventLabel"))
        self.label_currentStatus = QtGui.QLabel(self.tab_label_species)
        self.label_currentStatus.setGeometry(QtCore.QRect(30, 510, 621, 17))
        self.label_currentStatus.setObjectName(_fromUtf8("label_currentStatus"))
        self.checkBox_scaledZoom = QtGui.QCheckBox(self.tab_label_species)
        self.checkBox_scaledZoom.setGeometry(QtCore.QRect(710, 470, 131, 22))
        self.checkBox_scaledZoom.setChecked(True)
        self.checkBox_scaledZoom.setObjectName(_fromUtf8("checkBox_scaledZoom"))
        self.button_ShowFullSpectrogram = QtGui.QPushButton(self.tab_label_species)
        self.button_ShowFullSpectrogram.setGeometry(QtCore.QRect(30, 460, 231, 41))
        self.button_ShowFullSpectrogram.setObjectName(_fromUtf8("button_ShowFullSpectrogram"))
        self.button_ShowMarkedSpectrogram = QtGui.QPushButton(self.tab_label_species)
        self.button_ShowMarkedSpectrogram.setGeometry(QtCore.QRect(270, 460, 231, 41))
        self.button_ShowMarkedSpectrogram.setObjectName(_fromUtf8("button_ShowMarkedSpectrogram"))
        self.button_undo = QtGui.QPushButton(self.tab_label_species)
        self.button_undo.setGeometry(QtCore.QRect(510, 460, 111, 41))
        self.button_undo.setObjectName(_fromUtf8("button_undo"))
        self.tabWidget.addTab(self.tab_label_species, _fromUtf8(""))
        self.tab_label_action = QtGui.QWidget()
        self.tab_label_action.setObjectName(_fromUtf8("tab_label_action"))
        self.frame_eventview_action = QtGui.QFrame(self.tab_label_action)
        self.frame_eventview_action.setGeometry(QtCore.QRect(30, 40, 821, 411))
        self.frame_eventview_action.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_eventview_action.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_eventview_action.setObjectName(_fromUtf8("frame_eventview_action"))
        self.label_imageshow_action = QtGui.QLabel(self.frame_eventview_action)
        self.label_imageshow_action.setGeometry(QtCore.QRect(10, 10, 791, 391))
        self.label_imageshow_action.setAlignment(QtCore.Qt.AlignCenter)
        self.label_imageshow_action.setObjectName(_fromUtf8("label_imageshow_action"))
        self.frame = QtGui.QFrame(self.tab_label_action)
        self.frame.setGeometry(QtCore.QRect(70, 510, 211, 221))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.radioButton = QtGui.QRadioButton(self.frame)
        self.radioButton.setGeometry(QtCore.QRect(10, 10, 191, 22))
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.radioButton_2 = QtGui.QRadioButton(self.frame)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 40, 191, 22))
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.radioButton_3 = QtGui.QRadioButton(self.frame)
        self.radioButton_3.setGeometry(QtCore.QRect(10, 70, 191, 22))
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.radioButton_4 = QtGui.QRadioButton(self.frame)
        self.radioButton_4.setGeometry(QtCore.QRect(10, 100, 191, 22))
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.radioButton_5 = QtGui.QRadioButton(self.frame)
        self.radioButton_5.setGeometry(QtCore.QRect(10, 160, 191, 22))
        self.radioButton_5.setObjectName(_fromUtf8("radioButton_5"))
        self.radioButton_6 = QtGui.QRadioButton(self.frame)
        self.radioButton_6.setGeometry(QtCore.QRect(10, 130, 191, 22))
        self.radioButton_6.setObjectName(_fromUtf8("radioButton_6"))
        self.radioButton_7 = QtGui.QRadioButton(self.frame)
        self.radioButton_7.setGeometry(QtCore.QRect(10, 190, 191, 22))
        self.radioButton_7.setObjectName(_fromUtf8("radioButton_7"))
        self.label_ConstSelectSpecies = QtGui.QLabel(self.tab_label_action)
        self.label_ConstSelectSpecies.setGeometry(QtCore.QRect(110, 480, 121, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstSelectSpecies.setFont(font)
        self.label_ConstSelectSpecies.setObjectName(_fromUtf8("label_ConstSelectSpecies"))
        self.frame_2 = QtGui.QFrame(self.tab_label_action)
        self.frame_2.setGeometry(QtCore.QRect(450, 480, 261, 351))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.pushButton = QtGui.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(20, 30, 211, 41))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 90, 211, 41))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 150, 211, 41))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_4 = QtGui.QPushButton(self.frame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 210, 211, 41))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.pushButton_5 = QtGui.QPushButton(self.frame_2)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 270, 211, 41))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.frame_status_2 = QtGui.QFrame(self.tab_label_action)
        self.frame_status_2.setGeometry(QtCore.QRect(870, 10, 301, 911))
        self.frame_status_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_status_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_status_2.setObjectName(_fromUtf8("frame_status_2"))
        self.label_ConstEventName_2 = QtGui.QLabel(self.frame_status_2)
        self.label_ConstEventName_2.setGeometry(QtCore.QRect(10, 10, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstEventName_2.setFont(font)
        self.label_ConstEventName_2.setObjectName(_fromUtf8("label_ConstEventName_2"))
        self.line_22 = QtGui.QFrame(self.frame_status_2)
        self.line_22.setGeometry(QtCore.QRect(10, 50, 281, 16))
        self.line_22.setFrameShape(QtGui.QFrame.HLine)
        self.line_22.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_22.setObjectName(_fromUtf8("line_22"))
        self.label_ConstEventNo_2 = QtGui.QLabel(self.frame_status_2)
        self.label_ConstEventNo_2.setGeometry(QtCore.QRect(10, 60, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstEventNo_2.setFont(font)
        self.label_ConstEventNo_2.setObjectName(_fromUtf8("label_ConstEventNo_2"))
        self.line_23 = QtGui.QFrame(self.frame_status_2)
        self.line_23.setGeometry(QtCore.QRect(10, 100, 231, 16))
        self.line_23.setFrameShape(QtGui.QFrame.HLine)
        self.line_23.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_23.setObjectName(_fromUtf8("line_23"))
        self.label_ConstDate_2 = QtGui.QLabel(self.frame_status_2)
        self.label_ConstDate_2.setGeometry(QtCore.QRect(10, 110, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstDate_2.setFont(font)
        self.label_ConstDate_2.setObjectName(_fromUtf8("label_ConstDate_2"))
        self.line_24 = QtGui.QFrame(self.frame_status_2)
        self.line_24.setGeometry(QtCore.QRect(10, 150, 231, 16))
        self.line_24.setFrameShape(QtGui.QFrame.HLine)
        self.line_24.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_24.setObjectName(_fromUtf8("line_24"))
        self.label_EventName_2 = QtGui.QLabel(self.frame_status_2)
        self.label_EventName_2.setGeometry(QtCore.QRect(10, 30, 281, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_EventName_2.setFont(font)
        self.label_EventName_2.setObjectName(_fromUtf8("label_EventName_2"))
        self.label_EventNo_2 = QtGui.QLabel(self.frame_status_2)
        self.label_EventNo_2.setGeometry(QtCore.QRect(10, 80, 231, 17))
        self.label_EventNo_2.setObjectName(_fromUtf8("label_EventNo_2"))
        self.label_Date_2 = QtGui.QLabel(self.frame_status_2)
        self.label_Date_2.setGeometry(QtCore.QRect(10, 130, 231, 17))
        self.label_Date_2.setObjectName(_fromUtf8("label_Date_2"))
        self.line_25 = QtGui.QFrame(self.frame_status_2)
        self.line_25.setGeometry(QtCore.QRect(10, 300, 231, 16))
        self.line_25.setFrameShape(QtGui.QFrame.HLine)
        self.line_25.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_25.setObjectName(_fromUtf8("line_25"))
        self.label_maxFreq_2 = QtGui.QLabel(self.frame_status_2)
        self.label_maxFreq_2.setGeometry(QtCore.QRect(10, 230, 231, 17))
        self.label_maxFreq_2.setObjectName(_fromUtf8("label_maxFreq_2"))
        self.label_ConstMaxFreq_2 = QtGui.QLabel(self.frame_status_2)
        self.label_ConstMaxFreq_2.setGeometry(QtCore.QRect(10, 210, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstMaxFreq_2.setFont(font)
        self.label_ConstMaxFreq_2.setObjectName(_fromUtf8("label_ConstMaxFreq_2"))
        self.label_MinFreq_2 = QtGui.QLabel(self.frame_status_2)
        self.label_MinFreq_2.setGeometry(QtCore.QRect(10, 280, 231, 17))
        self.label_MinFreq_2.setObjectName(_fromUtf8("label_MinFreq_2"))
        self.line_26 = QtGui.QFrame(self.frame_status_2)
        self.line_26.setGeometry(QtCore.QRect(10, 240, 231, 16))
        self.line_26.setFrameShape(QtGui.QFrame.HLine)
        self.line_26.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_26.setObjectName(_fromUtf8("line_26"))
        self.label_ConstMinFreq_2 = QtGui.QLabel(self.frame_status_2)
        self.label_ConstMinFreq_2.setGeometry(QtCore.QRect(10, 260, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstMinFreq_2.setFont(font)
        self.label_ConstMinFreq_2.setObjectName(_fromUtf8("label_ConstMinFreq_2"))
        self.label_ConstDuration_2 = QtGui.QLabel(self.frame_status_2)
        self.label_ConstDuration_2.setGeometry(QtCore.QRect(10, 310, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstDuration_2.setFont(font)
        self.label_ConstDuration_2.setObjectName(_fromUtf8("label_ConstDuration_2"))
        self.line_27 = QtGui.QFrame(self.frame_status_2)
        self.line_27.setGeometry(QtCore.QRect(10, 350, 231, 16))
        self.line_27.setFrameShape(QtGui.QFrame.HLine)
        self.line_27.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_27.setObjectName(_fromUtf8("line_27"))
        self.label_Duration_2 = QtGui.QLabel(self.frame_status_2)
        self.label_Duration_2.setGeometry(QtCore.QRect(10, 330, 231, 17))
        self.label_Duration_2.setObjectName(_fromUtf8("label_Duration_2"))
        self.label_ConstFrontLine_12 = QtGui.QLabel(self.frame_status_2)
        self.label_ConstFrontLine_12.setGeometry(QtCore.QRect(10, 360, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstFrontLine_12.setFont(font)
        self.label_ConstFrontLine_12.setObjectName(_fromUtf8("label_ConstFrontLine_12"))
        self.line_28 = QtGui.QFrame(self.frame_status_2)
        self.line_28.setGeometry(QtCore.QRect(10, 400, 231, 16))
        self.line_28.setFrameShape(QtGui.QFrame.HLine)
        self.line_28.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_28.setObjectName(_fromUtf8("line_28"))
        self.label_FrontLine_12 = QtGui.QLabel(self.frame_status_2)
        self.label_FrontLine_12.setGeometry(QtCore.QRect(10, 380, 231, 17))
        self.label_FrontLine_12.setObjectName(_fromUtf8("label_FrontLine_12"))
        self.label_ConstFrontLine_13 = QtGui.QLabel(self.frame_status_2)
        self.label_ConstFrontLine_13.setGeometry(QtCore.QRect(10, 410, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstFrontLine_13.setFont(font)
        self.label_ConstFrontLine_13.setObjectName(_fromUtf8("label_ConstFrontLine_13"))
        self.line_29 = QtGui.QFrame(self.frame_status_2)
        self.line_29.setGeometry(QtCore.QRect(10, 450, 231, 16))
        self.line_29.setFrameShape(QtGui.QFrame.HLine)
        self.line_29.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_29.setObjectName(_fromUtf8("line_29"))
        self.label_FrontLine_13 = QtGui.QLabel(self.frame_status_2)
        self.label_FrontLine_13.setGeometry(QtCore.QRect(10, 430, 231, 17))
        self.label_FrontLine_13.setObjectName(_fromUtf8("label_FrontLine_13"))
        self.label_ConstFrontLine_14 = QtGui.QLabel(self.frame_status_2)
        self.label_ConstFrontLine_14.setGeometry(QtCore.QRect(10, 460, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstFrontLine_14.setFont(font)
        self.label_ConstFrontLine_14.setObjectName(_fromUtf8("label_ConstFrontLine_14"))
        self.line_30 = QtGui.QFrame(self.frame_status_2)
        self.line_30.setGeometry(QtCore.QRect(10, 500, 231, 16))
        self.line_30.setFrameShape(QtGui.QFrame.HLine)
        self.line_30.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_30.setObjectName(_fromUtf8("line_30"))
        self.label_FrontLine_14 = QtGui.QLabel(self.frame_status_2)
        self.label_FrontLine_14.setGeometry(QtCore.QRect(10, 480, 231, 17))
        self.label_FrontLine_14.setObjectName(_fromUtf8("label_FrontLine_14"))
        self.label_ConstFrontLine_15 = QtGui.QLabel(self.frame_status_2)
        self.label_ConstFrontLine_15.setGeometry(QtCore.QRect(10, 510, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstFrontLine_15.setFont(font)
        self.label_ConstFrontLine_15.setObjectName(_fromUtf8("label_ConstFrontLine_15"))
        self.line_31 = QtGui.QFrame(self.frame_status_2)
        self.line_31.setGeometry(QtCore.QRect(10, 550, 231, 16))
        self.line_31.setFrameShape(QtGui.QFrame.HLine)
        self.line_31.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_31.setObjectName(_fromUtf8("line_31"))
        self.label_FrontLine_15 = QtGui.QLabel(self.frame_status_2)
        self.label_FrontLine_15.setGeometry(QtCore.QRect(10, 530, 231, 17))
        self.label_FrontLine_15.setObjectName(_fromUtf8("label_FrontLine_15"))
        self.label_ConstFrontLine_16 = QtGui.QLabel(self.frame_status_2)
        self.label_ConstFrontLine_16.setGeometry(QtCore.QRect(10, 560, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstFrontLine_16.setFont(font)
        self.label_ConstFrontLine_16.setObjectName(_fromUtf8("label_ConstFrontLine_16"))
        self.line_32 = QtGui.QFrame(self.frame_status_2)
        self.line_32.setGeometry(QtCore.QRect(10, 610, 231, 16))
        self.line_32.setFrameShape(QtGui.QFrame.HLine)
        self.line_32.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_32.setObjectName(_fromUtf8("line_32"))
        self.label_FrontLine_16 = QtGui.QLabel(self.frame_status_2)
        self.label_FrontLine_16.setGeometry(QtCore.QRect(10, 580, 231, 17))
        self.label_FrontLine_16.setObjectName(_fromUtf8("label_FrontLine_16"))
        self.label_ConstFrontLine_17 = QtGui.QLabel(self.frame_status_2)
        self.label_ConstFrontLine_17.setGeometry(QtCore.QRect(10, 610, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstFrontLine_17.setFont(font)
        self.label_ConstFrontLine_17.setObjectName(_fromUtf8("label_ConstFrontLine_17"))
        self.line_33 = QtGui.QFrame(self.frame_status_2)
        self.line_33.setGeometry(QtCore.QRect(10, 650, 231, 16))
        self.line_33.setFrameShape(QtGui.QFrame.HLine)
        self.line_33.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_33.setObjectName(_fromUtf8("line_33"))
        self.label_FrontLine_17 = QtGui.QLabel(self.frame_status_2)
        self.label_FrontLine_17.setGeometry(QtCore.QRect(10, 630, 231, 17))
        self.label_FrontLine_17.setObjectName(_fromUtf8("label_FrontLine_17"))
        self.label_ConstFrontLine_18 = QtGui.QLabel(self.frame_status_2)
        self.label_ConstFrontLine_18.setGeometry(QtCore.QRect(10, 660, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstFrontLine_18.setFont(font)
        self.label_ConstFrontLine_18.setObjectName(_fromUtf8("label_ConstFrontLine_18"))
        self.line_34 = QtGui.QFrame(self.frame_status_2)
        self.line_34.setGeometry(QtCore.QRect(10, 700, 231, 16))
        self.line_34.setFrameShape(QtGui.QFrame.HLine)
        self.line_34.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_34.setObjectName(_fromUtf8("line_34"))
        self.label_FrontLine_18 = QtGui.QLabel(self.frame_status_2)
        self.label_FrontLine_18.setGeometry(QtCore.QRect(10, 680, 231, 17))
        self.label_FrontLine_18.setObjectName(_fromUtf8("label_FrontLine_18"))
        self.label_ConstFrontLine_19 = QtGui.QLabel(self.frame_status_2)
        self.label_ConstFrontLine_19.setGeometry(QtCore.QRect(10, 710, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstFrontLine_19.setFont(font)
        self.label_ConstFrontLine_19.setObjectName(_fromUtf8("label_ConstFrontLine_19"))
        self.line_35 = QtGui.QFrame(self.frame_status_2)
        self.line_35.setGeometry(QtCore.QRect(10, 750, 231, 16))
        self.line_35.setFrameShape(QtGui.QFrame.HLine)
        self.line_35.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_35.setObjectName(_fromUtf8("line_35"))
        self.label_FrontLine_19 = QtGui.QLabel(self.frame_status_2)
        self.label_FrontLine_19.setGeometry(QtCore.QRect(10, 730, 231, 17))
        self.label_FrontLine_19.setObjectName(_fromUtf8("label_FrontLine_19"))
        self.label_ConstFrontLine_20 = QtGui.QLabel(self.frame_status_2)
        self.label_ConstFrontLine_20.setGeometry(QtCore.QRect(10, 760, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstFrontLine_20.setFont(font)
        self.label_ConstFrontLine_20.setObjectName(_fromUtf8("label_ConstFrontLine_20"))
        self.line_36 = QtGui.QFrame(self.frame_status_2)
        self.line_36.setGeometry(QtCore.QRect(10, 800, 231, 16))
        self.line_36.setFrameShape(QtGui.QFrame.HLine)
        self.line_36.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_36.setObjectName(_fromUtf8("line_36"))
        self.label_FrontLine_20 = QtGui.QLabel(self.frame_status_2)
        self.label_FrontLine_20.setGeometry(QtCore.QRect(10, 780, 231, 17))
        self.label_FrontLine_20.setObjectName(_fromUtf8("label_FrontLine_20"))
        self.label_ConstFrontLine_21 = QtGui.QLabel(self.frame_status_2)
        self.label_ConstFrontLine_21.setGeometry(QtCore.QRect(10, 810, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstFrontLine_21.setFont(font)
        self.label_ConstFrontLine_21.setObjectName(_fromUtf8("label_ConstFrontLine_21"))
        self.line_37 = QtGui.QFrame(self.frame_status_2)
        self.line_37.setGeometry(QtCore.QRect(10, 850, 231, 16))
        self.line_37.setFrameShape(QtGui.QFrame.HLine)
        self.line_37.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_37.setObjectName(_fromUtf8("line_37"))
        self.label_FrontLine_21 = QtGui.QLabel(self.frame_status_2)
        self.label_FrontLine_21.setGeometry(QtCore.QRect(10, 830, 231, 17))
        self.label_FrontLine_21.setObjectName(_fromUtf8("label_FrontLine_21"))
        self.label_ConstTime_2 = QtGui.QLabel(self.frame_status_2)
        self.label_ConstTime_2.setGeometry(QtCore.QRect(10, 160, 66, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstTime_2.setFont(font)
        self.label_ConstTime_2.setObjectName(_fromUtf8("label_ConstTime_2"))
        self.line_38 = QtGui.QFrame(self.frame_status_2)
        self.line_38.setGeometry(QtCore.QRect(10, 200, 231, 16))
        self.line_38.setFrameShape(QtGui.QFrame.HLine)
        self.line_38.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_38.setObjectName(_fromUtf8("line_38"))
        self.label_time_2 = QtGui.QLabel(self.frame_status_2)
        self.label_time_2.setGeometry(QtCore.QRect(10, 180, 231, 17))
        self.label_time_2.setObjectName(_fromUtf8("label_time_2"))
        self.label_ConstFrontLine_22 = QtGui.QLabel(self.frame_status_2)
        self.label_ConstFrontLine_22.setGeometry(QtCore.QRect(10, 860, 241, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ConstFrontLine_22.setFont(font)
        self.label_ConstFrontLine_22.setObjectName(_fromUtf8("label_ConstFrontLine_22"))
        self.label_FrontLine_22 = QtGui.QLabel(self.frame_status_2)
        self.label_FrontLine_22.setGeometry(QtCore.QRect(10, 880, 231, 17))
        self.label_FrontLine_22.setObjectName(_fromUtf8("label_FrontLine_22"))
        self.line_39 = QtGui.QFrame(self.frame_status_2)
        self.line_39.setGeometry(QtCore.QRect(10, 900, 231, 16))
        self.line_39.setFrameShape(QtGui.QFrame.HLine)
        self.line_39.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_39.setObjectName(_fromUtf8("line_39"))
        self.tabWidget.addTab(self.tab_label_action, _fromUtf8(""))
        self.tab_reconstructor = QtGui.QWidget()
        self.tab_reconstructor.setObjectName(_fromUtf8("tab_reconstructor"))
        self.label_Const_Recontructor = QtGui.QLabel(self.tab_reconstructor)
        self.label_Const_Recontructor.setGeometry(QtCore.QRect(20, 10, 1031, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_Const_Recontructor.setFont(font)
        self.label_Const_Recontructor.setObjectName(_fromUtf8("label_Const_Recontructor"))
        self.button_loaddatabaseReconstruct = QtGui.QPushButton(self.tab_reconstructor)
        self.button_loaddatabaseReconstruct.setGeometry(QtCore.QRect(30, 80, 131, 41))
        self.button_loaddatabaseReconstruct.setObjectName(_fromUtf8("button_loaddatabaseReconstruct"))
        self.label_database_name_Reconstruct = QtGui.QLabel(self.tab_reconstructor)
        self.label_database_name_Reconstruct.setGeometry(QtCore.QRect(30, 130, 931, 17))
        self.label_database_name_Reconstruct.setObjectName(_fromUtf8("label_database_name_Reconstruct"))
        self.label_outputDirectory_Reconstruct = QtGui.QLabel(self.tab_reconstructor)
        self.label_outputDirectory_Reconstruct.setGeometry(QtCore.QRect(30, 220, 811, 20))
        self.label_outputDirectory_Reconstruct.setObjectName(_fromUtf8("label_outputDirectory_Reconstruct"))
        self.pushButton_SetOutputDirectory_Reconstruct = QtGui.QPushButton(self.tab_reconstructor)
        self.pushButton_SetOutputDirectory_Reconstruct.setGeometry(QtCore.QRect(30, 180, 171, 31))
        self.pushButton_SetOutputDirectory_Reconstruct.setObjectName(_fromUtf8("pushButton_SetOutputDirectory_Reconstruct"))
        self.line_20 = QtGui.QFrame(self.tab_reconstructor)
        self.line_20.setGeometry(QtCore.QRect(20, 270, 1151, 16))
        self.line_20.setFrameShape(QtGui.QFrame.HLine)
        self.line_20.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_20.setObjectName(_fromUtf8("line_20"))
        self.button_Recontructor = QtGui.QPushButton(self.tab_reconstructor)
        self.button_Recontructor.setGeometry(QtCore.QRect(480, 780, 211, 41))
        self.button_Recontructor.setCheckable(False)
        self.button_Recontructor.setObjectName(_fromUtf8("button_Recontructor"))
        self.textEdit_overview_Recontructor = QtGui.QTextEdit(self.tab_reconstructor)
        self.textEdit_overview_Recontructor.setGeometry(QtCore.QRect(100, 320, 991, 371))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_overview_Recontructor.setFont(font)
        self.textEdit_overview_Recontructor.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.textEdit_overview_Recontructor.setReadOnly(True)
        self.textEdit_overview_Recontructor.setObjectName(_fromUtf8("textEdit_overview_Recontructor"))
        self.progressBar_Recontructor = QtGui.QProgressBar(self.tab_reconstructor)
        self.progressBar_Recontructor.setGeometry(QtCore.QRect(100, 710, 991, 23))
        self.progressBar_Recontructor.setProperty("value", 0)
        self.progressBar_Recontructor.setObjectName(_fromUtf8("progressBar_Recontructor"))
        self.label_status_Recontructor = QtGui.QLabel(self.tab_reconstructor)
        self.label_status_Recontructor.setGeometry(QtCore.QRect(100, 300, 66, 17))
        self.label_status_Recontructor.setObjectName(_fromUtf8("label_status_Recontructor"))
        self.tabWidget.addTab(self.tab_reconstructor, _fromUtf8(""))
        BatWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(BatWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(BatWindow)

    def retranslateUi(self, BatWindow):
        BatWindow.setWindowTitle(_translate("BatWindow", "Bat GUI Analyzer", None))
        self.button_start.setText(_translate("BatWindow", "Start Analyzing", None))
        self.label_status.setText(_translate("BatWindow", "Status", None))
        self.pushButton_createSpectrogram.setText(_translate("BatWindow", "Create Spectrogram", None))
        self.pushButton_SetInputDirectory.setWhatsThis(_translate("BatWindow", "Select the directory containing the .s16 files", None))
        self.pushButton_SetInputDirectory.setText(_translate("BatWindow", "Select Input Directory", None))
        self.pushButton_SetOutputDirectory.setWhatsThis(_translate("BatWindow", "Select the output directory where all the generated files will be saved to", None))
        self.pushButton_SetOutputDirectory.setText(_translate("BatWindow", "Select Output Directory", None))
        self.label_inputDirectory.setText(_translate("BatWindow", "/home/anoch/Documents/BatSamples", None))
        self.label_outputDirectory.setText(_translate("BatWindow", "/home/anoch/Documents/BatSamples", None))
        self.label_Channel.setText(_translate("BatWindow", "Select Channel:", None))
        self.radioButton_channel_1.setText(_translate("BatWindow", "Channel 1", None))
        self.radioButton_channel_2.setText(_translate("BatWindow", "Channel 2", None))
        self.radioButton_channel_3.setText(_translate("BatWindow", "Channel 3", None))
        self.radioButton_channel_4.setText(_translate("BatWindow", "Channel 4", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_analyze), _translate("BatWindow", "Analyze", None))
        self.button_loaddatabase.setText(_translate("BatWindow", "Load Database", None))
        self.label_database_name.setText(_translate("BatWindow", "No Database Selected", None))
        self.label_ConstEventName.setText(_translate("BatWindow", "Event Name:", None))
        self.label_ConstEventNo.setText(_translate("BatWindow", "Event no.:", None))
        self.label_ConstDate.setText(_translate("BatWindow", "Date:", None))
        self.label_EventName.setText(_translate("BatWindow", "N/A", None))
        self.label_EventNo.setText(_translate("BatWindow", "N/A", None))
        self.label_Date.setText(_translate("BatWindow", "N/A", None))
        self.label_maxFreq.setText(_translate("BatWindow", "N/A", None))
        self.label_ConstMaxFreq.setText(_translate("BatWindow", "Max Frequency [kHz]:", None))
        self.label_MinFreq.setText(_translate("BatWindow", "N/A", None))
        self.label_ConstMinFreq.setText(_translate("BatWindow", "Min Frequency [kHz]:", None))
        self.label_ConstDuration.setText(_translate("BatWindow", "Duration [ms]:", None))
        self.label_Duration.setText(_translate("BatWindow", "N/A", None))
        self.label_ConstFrontLine_1.setText(_translate("BatWindow", "Front Line 1:", None))
        self.label_FrontLine_1.setText(_translate("BatWindow", "N/A", None))
        self.label_ConstFrontLine_2.setText(_translate("BatWindow", "Front Line 2:", None))
        self.label_FrontLine_2.setText(_translate("BatWindow", "N/A", None))
        self.label_ConstFrontLine_3.setText(_translate("BatWindow", "Front Line 3:", None))
        self.label_FrontLine_3.setText(_translate("BatWindow", "N/A", None))
        self.label_ConstFrontLine_4.setText(_translate("BatWindow", "Front Line 4:", None))
        self.label_FrontLine_4.setText(_translate("BatWindow", "N/A", None))
        self.label_ConstFrontLine_5.setText(_translate("BatWindow", "Front Line 5:", None))
        self.label_FrontLine_5.setText(_translate("BatWindow", "N/A", None))
        self.label_ConstFrontLine_6.setText(_translate("BatWindow", "Front Line 6:", None))
        self.label_FrontLine_6.setText(_translate("BatWindow", "N/A", None))
        self.label_ConstFrontLine_7.setText(_translate("BatWindow", "Front Line 7:", None))
        self.label_FrontLine_7.setText(_translate("BatWindow", "N/A", None))
        self.label_ConstFrontLine_8.setText(_translate("BatWindow", "Front Line 8:", None))
        self.label_FrontLine_8.setText(_translate("BatWindow", "N/A", None))
        self.label_ConstFrontLine_9.setText(_translate("BatWindow", "Front Line 9:", None))
        self.label_FrontLine_9.setText(_translate("BatWindow", "N/A", None))
        self.label_ConstFrontLine_10.setText(_translate("BatWindow", "Front Line 10:", None))
        self.label_FrontLine_10.setText(_translate("BatWindow", "N/A", None))
        self.label_ConstTime.setText(_translate("BatWindow", "Time:", None))
        self.label_time.setText(_translate("BatWindow", "N/A", None))
        self.label_ConstFrontLine_11.setText(_translate("BatWindow", "Front Line 11:", None))
        self.label_FrontLine_11.setText(_translate("BatWindow", "N/A", None))
        self.label_imageshow.setText(_translate("BatWindow", "Event Viewer", None))
        self.button_noise.setText(_translate("BatWindow", "(7) Noise", None))
        self.button_MyotisDaubentonii.setText(_translate("BatWindow", "(3) Myotis daubentonii", None))
        self.button_pipistrellusNathusii.setText(_translate("BatWindow", "(5) Pipistrellus nathusii", None))
        self.button_NyctalusNoctula.setText(_translate("BatWindow", "(6) Nyctalus noctula", None))
        self.button_MyotisDasycneme.setText(_translate("BatWindow", "(4) Myotis dasycneme", None))
        self.button_EptesicusSerotinus.setText(_translate("BatWindow", "(1) Eptesicus serotinus", None))
        self.button_PipistrellusPygmaeus.setText(_translate("BatWindow", "(2) Pipistrellus pygmaeus", None))
        self.button_OtherSpecies.setText(_translate("BatWindow", "(8) Other Species", None))
        self.button_SomethingElse.setText(_translate("BatWindow", "(9) Something else", None))
        self.label_currentStatus.setText(_translate("BatWindow", "N/A", None))
        self.checkBox_scaledZoom.setText(_translate("BatWindow", "Fit To Screen (z)", None))
        self.button_ShowFullSpectrogram.setText(_translate("BatWindow", "Show Full Spectrogram (s)", None))
        self.button_ShowMarkedSpectrogram.setText(_translate("BatWindow", "Show Marked Spectrogram (m)", None))
        self.button_undo.setText(_translate("BatWindow", "(u) Undo", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_label_species), _translate("BatWindow", "Label Species", None))
        self.label_imageshow_action.setText(_translate("BatWindow", "Event Viewer", None))
        self.radioButton.setText(_translate("BatWindow", "Eptesicus serotinus", None))
        self.radioButton_2.setText(_translate("BatWindow", "Pipistrellus pygmaeus", None))
        self.radioButton_3.setText(_translate("BatWindow", "Myotis daubentonii", None))
        self.radioButton_4.setText(_translate("BatWindow", "Myotis dasycneme", None))
        self.radioButton_5.setText(_translate("BatWindow", "Nyctalus noctula", None))
        self.radioButton_6.setText(_translate("BatWindow", "Pipistrellus nathusii", None))
        self.radioButton_7.setText(_translate("BatWindow", "Something Else", None))
        self.label_ConstSelectSpecies.setText(_translate("BatWindow", "Select Species:", None))
        self.pushButton.setText(_translate("BatWindow", "(1) Echolocation", None))
        self.pushButton_2.setText(_translate("BatWindow", "(2) Social Call", None))
        self.pushButton_3.setText(_translate("BatWindow", "(3) Foraging", None))
        self.pushButton_4.setText(_translate("BatWindow", "(4) Echolocation / Social Call", None))
        self.pushButton_5.setText(_translate("BatWindow", "(5) Something Else", None))
        self.label_ConstEventName_2.setText(_translate("BatWindow", "Event Name:", None))
        self.label_ConstEventNo_2.setText(_translate("BatWindow", "Event no.:", None))
        self.label_ConstDate_2.setText(_translate("BatWindow", "Date:", None))
        self.label_EventName_2.setText(_translate("BatWindow", "N/A", None))
        self.label_EventNo_2.setText(_translate("BatWindow", "N/A", None))
        self.label_Date_2.setText(_translate("BatWindow", "N/A", None))
        self.label_maxFreq_2.setText(_translate("BatWindow", "N/A", None))
        self.label_ConstMaxFreq_2.setText(_translate("BatWindow", "Max Frequency [kHz]:", None))
        self.label_MinFreq_2.setText(_translate("BatWindow", "N/A", None))
        self.label_ConstMinFreq_2.setText(_translate("BatWindow", "Min Frequency [kHz]:", None))
        self.label_ConstDuration_2.setText(_translate("BatWindow", "Duration [ms]:", None))
        self.label_Duration_2.setText(_translate("BatWindow", "N/A", None))
        self.label_ConstFrontLine_12.setText(_translate("BatWindow", "Front Line 1:", None))
        self.label_FrontLine_12.setText(_translate("BatWindow", "N/A", None))
        self.label_ConstFrontLine_13.setText(_translate("BatWindow", "Front Line 2:", None))
        self.label_FrontLine_13.setText(_translate("BatWindow", "N/A", None))
        self.label_ConstFrontLine_14.setText(_translate("BatWindow", "Front Line 3:", None))
        self.label_FrontLine_14.setText(_translate("BatWindow", "N/A", None))
        self.label_ConstFrontLine_15.setText(_translate("BatWindow", "Front Line 4:", None))
        self.label_FrontLine_15.setText(_translate("BatWindow", "N/A", None))
        self.label_ConstFrontLine_16.setText(_translate("BatWindow", "Front Line 5:", None))
        self.label_FrontLine_16.setText(_translate("BatWindow", "N/A", None))
        self.label_ConstFrontLine_17.setText(_translate("BatWindow", "Front Line 6:", None))
        self.label_FrontLine_17.setText(_translate("BatWindow", "N/A", None))
        self.label_ConstFrontLine_18.setText(_translate("BatWindow", "Front Line 7:", None))
        self.label_FrontLine_18.setText(_translate("BatWindow", "N/A", None))
        self.label_ConstFrontLine_19.setText(_translate("BatWindow", "Front Line 8:", None))
        self.label_FrontLine_19.setText(_translate("BatWindow", "N/A", None))
        self.label_ConstFrontLine_20.setText(_translate("BatWindow", "Front Line 9:", None))
        self.label_FrontLine_20.setText(_translate("BatWindow", "N/A", None))
        self.label_ConstFrontLine_21.setText(_translate("BatWindow", "Front Line 10:", None))
        self.label_FrontLine_21.setText(_translate("BatWindow", "N/A", None))
        self.label_ConstTime_2.setText(_translate("BatWindow", "Time:", None))
        self.label_time_2.setText(_translate("BatWindow", "N/A", None))
        self.label_ConstFrontLine_22.setText(_translate("BatWindow", "Front Line 11:", None))
        self.label_FrontLine_22.setText(_translate("BatWindow", "N/A", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_label_action), _translate("BatWindow", "Label Action", None))
        self.label_Const_Recontructor.setText(_translate("BatWindow", "Generate images of events, spectrogram and marked spectrogram from HDF5 file", None))
        self.button_loaddatabaseReconstruct.setText(_translate("BatWindow", "Load Database", None))
        self.label_database_name_Reconstruct.setText(_translate("BatWindow", "No Database Selected", None))
        self.label_outputDirectory_Reconstruct.setText(_translate("BatWindow", "/home/anoch/Documents/BatSamples", None))
        self.pushButton_SetOutputDirectory_Reconstruct.setWhatsThis(_translate("BatWindow", "Select the output directory where all the generated files will be saved to", None))
        self.pushButton_SetOutputDirectory_Reconstruct.setText(_translate("BatWindow", "Select Output Directory", None))
        self.button_Recontructor.setText(_translate("BatWindow", "Recontruct Images", None))
        self.label_status_Recontructor.setText(_translate("BatWindow", "Status", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_reconstructor), _translate("BatWindow", "Reconstructor", None))

